import { Azeret_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/Navbar";
import Player from "./ui/PlayerTest";
import Footer from "./ui/Footer";

const inter = Azeret_Mono({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className + " flex flex-col"}>
        <Navbar/>
        {children}
        <Footer/>
        <Player/>
      </body>
    </html>
  );
}
