import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/Navbar";
import Player from "./ui/Player";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
        <Player show={"The Pop Show"} 
                dj={"with " + "DJ Shrimp"} 
                time={"9:00 am - 10:00 am"} 
                cover={""} // will be link
                music={"Flamingo"} 
                artist={"Kero Kero Bonito"}/>
      </body>
    </html>
  );
}
